name: exe_only_asana_weekly_todo_notification_for_slack_by_workflow_dispatch

on:
  workflow_dispatch:

jobs:
  asana_notification_for_slack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run asana_weekly_todo_notification_for_slack.py
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          WORKSPACE_ID: ${{ secrets.WORKSPACE_ID }}
          PROJIECT_ID_DEVELOP: ${{ secrets.PROJIECT_ID_DEVELOP }}
          PROJIECT_ID_DESIGN: ${{ secrets.PROJIECT_ID_DESIGN }}
          PROJIECT_ID_GENERAL_AFFAIRS: ${{ secrets.PROJIECT_ID_GENERAL_AFFAIRS }}
          PROJIECT_ID_SALES: ${{ secrets.PROJIECT_ID_SALES }}
          PROJIECT_ID_HUMAN_RESOURCE: ${{ secrets.PROJIECT_ID_HUMAN_RESOURCE }}
          WEBHOOK_URL_DEFAULT: ${{ secrets.WEBHOOK_URL_DEFAULT }}
          WEBHOOK_URL_DEVELOP: ${{ secrets.WEBHOOK_URL_DEVELOP }}
          WEBHOOK_URL_DESIGN: ${{ secrets.WEBHOOK_URL_DESIGN }}
          WEBHOOK_URL_GENERAL_AFFAIRS: ${{ secrets.WEBHOOK_URL_GENERAL_AFFAIRS }}
          WEBHOOK_URL_SALES: ${{ secrets.WEBHOOK_URL_SALES }}
          WEBHOOK_URL_HUMAN_RESOURCE: ${{ secrets.WEBHOOK_URL_HUMAN_RESOURCE }}
          WEBHOOK_URL_WEEKLY_TODO_FOR_NOTION: ${{ secrets.WEBHOOK_URL_WEEKLY_TODO_FOR_NOTION }}
          WEBHOOK_URL_WEEKLY_TODO_FOR_TICKTICK: ${{ secrets.WEBHOOK_URL_WEEKLY_TODO_FOR_TICKTICK }}
          CHANNEL_ID_DEFAULT: ${{ secrets.CHANNEL_ID_DEFAULT }}
          CHANNEL_ID_WEEKLY_TODO_NOTIFICATION_FOR_NOTION: ${{ secrets.CHANNEL_ID_WEEKLY_TODO_NOTIFICATION_FOR_NOTION }}
          SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
          IS_DEBUG: ${{ secrets.IS_DEBUG }}
        run: python asana_weekly_todo_notification_for_slack.py
